# Generated by Django 5.0.3 on 2024-04-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generated_amount_history',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
