# Generated by Django 5.0.3 on 2024-04-15 10:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw_history',
            name='amount',
            field=models.DecimalField(decimal_places=1000, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='withdraw_history',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='withdraw_history',
            name='withdraw_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
