# Generated by Django 5.0.3 on 2024-04-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0002_alter_withdraw_history_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw_history',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
