# Generated by Django 5.0.3 on 2024-04-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0003_alter_withdraw_history_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw_history',
            name='account_nuber',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdraw_history',
            name='ifsc_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
