# Generated by Django 5.0.3 on 2024-04-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0005_rename_account_nuber_withdraw_history_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw_history',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
