# Generated by Django 5.0.3 on 2024-04-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0006_alter_withdraw_history_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw_history',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
