# Generated by Django 5.0.3 on 2024-04-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_wallet_model_wallet_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Payment_Id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.TextField(max_length=100)),
            ],
        ),
    ]
