# Generated by Django 5.0.3 on 2024-04-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_payment_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_details',
            name='payment_completed',
            field=models.BooleanField(default=False),
        ),
    ]
