# Generated by Django 5.0.3 on 2024-04-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_payment_details_payment_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_details',
            name='payment_amount',
            field=models.IntegerField(default=0.0),
        ),
    ]
