# Generated by Django 5.0.3 on 2024-04-12 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_payment_details_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_details',
            name='utr_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
