# Generated by Django 5.0.3 on 2024-04-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_alter_payment_details_utr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_details',
            name='payment_completed',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
