# Generated by Django 5.0.3 on 2024-04-03 06:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('e2f67116-0b40-4e8a-b79f-1d1fd4bbd32e'), editable=False, unique=True),
        ),
    ]
