# Generated by Django 5.0.3 on 2024-04-03 06:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_product_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('cb2301de-640b-4059-8217-2c8a5f795ab6'), editable=False, unique=True),
        ),
    ]
