# Generated by Django 5.0.3 on 2024-03-31 09:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_alter_user_model_email_token_alter_user_model_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='email_token',
            field=models.UUIDField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2abfb686-772b-4c07-97cf-2ebaae05c99a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
