# Generated by Django 5.0.3 on 2024-03-31 09:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0004_alter_user_model_email_token_alter_user_model_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='email_token',
            field=models.UUIDField(unique=True),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='id',
            field=models.UUIDField(default=uuid.UUID('570608c4-42b7-4ddf-8aeb-0ddf2b50a23b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
