# Generated by Django 5.0.3 on 2024-03-31 09:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_alter_user_model_email_token_alter_user_model_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='email_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='id',
            field=models.UUIDField(default=uuid.UUID('77532c52-eb36-4969-a73d-6f19c928462c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
