# Generated by Django 5.0.3 on 2024-03-31 09:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0006_alter_user_model_email_token_alter_user_model_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6ebfded1-58f7-4ade-955c-c807db241b1d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
