# Generated by Django 5.0.3 on 2024-03-31 09:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0007_alter_user_model_id_alter_user_model_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_model',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0feac2be-21ba-4366-b3f1-e7555aabd035'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
