# Generated by Django 5.0.3 on 2024-04-01 10:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0008_user_model_is_verified_alter_user_model_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6bfdb5f7-4b8b-4b9b-bbaf-892e5079ee1f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
