# Generated by Django 5.0.3 on 2024-04-01 10:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0009_alter_user_model_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_model',
            name='referal_id',
            field=models.UUIDField(default=uuid.UUID('902059b7-19fb-4353-a002-f87481af77fe'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='email',
            field=models.EmailField(editable=False, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d702395e-e91d-4b9c-9c16-bef2e961ed5c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
