# Generated by Django 5.0.3 on 2024-04-01 10:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0010_user_model_referal_id_alter_user_model_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c64f13fd-2cd6-4362-bef7-eafb818e79d5'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='referal_id',
            field=models.UUIDField(default=uuid.UUID('458fd962-508d-476f-bb71-0414440e8789'), editable=False, unique=True),
        ),
    ]
