# Generated by Django 5.0.3 on 2024-04-01 10:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0011_alter_user_model_id_alter_user_model_referal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_model',
            name='refered_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1c46b778-4e58-4cf1-b049-0486361daec6'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='referal_id',
            field=models.UUIDField(default=uuid.UUID('a9c749ac-48f5-47d0-852e-e49993029893'), editable=False, unique=True),
        ),
    ]
