# Generated by Django 5.0.3 on 2024-04-03 06:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0014_alter_user_model_id_alter_user_model_referal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7f79cb10-9d86-4dc2-9aa7-878d2ca1cb9a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='referal_id',
            field=models.UUIDField(default=uuid.UUID('341965ef-75d7-47ef-8464-aa69cc8e8aaa'), editable=False, unique=True),
        ),
    ]
