# Generated by Django 5.0.3 on 2024-04-03 06:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0016_alter_user_model_id_alter_user_model_referal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d8e09a7a-7999-4041-a334-da8172ce62a1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='referal_id',
            field=models.UUIDField(default=uuid.UUID('e319cacd-d8d9-4d84-9c5b-348cd893e64b'), editable=False, unique=True),
        ),
    ]
