# Generated by Django 5.0.3 on 2024-04-03 06:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0018_alter_user_model_id_alter_user_model_referal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5da29e61-677f-4a43-97dc-2e5dc98ae74b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='referal_id',
            field=models.UUIDField(default=uuid.UUID('9ba27a57-822e-47b1-bcbd-256669948fe0'), editable=False, unique=True),
        ),
    ]
