# Generated by Django 5.0.3 on 2024-04-12 09:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0023_alter_user_model_id_alter_user_model_referal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4230881b-7103-4741-b691-f29df4a5f311'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='referal_id',
            field=models.UUIDField(default=uuid.UUID('ba2f2d5f-a2b4-4423-b7b0-adf21ca94903'), editable=False, unique=True),
        ),
    ]
