# Generated by Django 5.0.3 on 2024-04-12 10:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0026_alter_user_model_id_alter_user_model_referal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4b86e7d7-5f7d-46cd-a5ad-32d921bac109'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='referal_id',
            field=models.UUIDField(default=uuid.UUID('fdc5397a-2fe7-4e9f-b4e7-b5858541618e'), editable=False, unique=True),
        ),
    ]
