# Generated by Django 5.0.3 on 2024-04-12 10:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0028_alter_user_model_id_alter_user_model_referal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7f8d2ccb-09ff-415e-a1f8-c57cae6fc6de'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='referal_id',
            field=models.UUIDField(default=uuid.UUID('6cfff5c4-314f-4d1f-b80d-1a5b1c9ac5ff'), editable=False, unique=True),
        ),
    ]
