# Generated by Django 5.0.3 on 2024-04-12 10:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0029_alter_user_model_id_alter_user_model_referal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5f1f1bfd-2bfb-4739-bc82-66ed13a2f663'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='referal_id',
            field=models.UUIDField(default=uuid.UUID('93012ee1-8679-4741-ba4a-23db22b7197a'), editable=False, unique=True),
        ),
    ]
