# Generated by Django 5.0.3 on 2024-04-12 10:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0031_alter_user_model_id_alter_user_model_referal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='id',
            field=models.UUIDField(default=uuid.UUID('704ae78a-dba3-452d-9bc1-a27e6f40a221'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='referal_id',
            field=models.UUIDField(default=uuid.UUID('4dad69a6-854f-447d-8dcc-de749675f2f9'), editable=False, unique=True),
        ),
    ]
