# Generated by Django 5.0.3 on 2024-04-12 10:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0035_alter_user_model_id_alter_user_model_referal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ab3a94e6-ce17-4872-a490-dd28144c5277'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='referal_id',
            field=models.UUIDField(default=uuid.UUID('46d7bc8b-988c-4d0a-8343-c842a07b7aa8'), editable=False, unique=True),
        ),
    ]
