# Generated by Django 5.0.3 on 2024-04-12 10:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0037_alter_user_model_id_alter_user_model_referal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='id',
            field=models.UUIDField(default=uuid.UUID('64c773c7-0bad-431c-9b5c-e8ac0b7059e3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='referal_id',
            field=models.UUIDField(default=uuid.UUID('22441868-0329-44a9-a3b6-ad3e23e8c556'), editable=False),
        ),
    ]
