# Generated by Django 5.0.3 on 2024-04-12 10:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0039_alter_user_model_id_alter_user_model_referal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='id',
            field=models.UUIDField(default=uuid.UUID('48a054ad-88d0-4a1f-84e2-7f32159b42db'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='referal_id',
            field=models.UUIDField(default=uuid.UUID('8140a5a1-8cfa-47c1-a1fc-fbb2542e9091'), unique=True),
        ),
    ]
