# Generated by Django 5.0.3 on 2024-04-12 10:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0042_alter_user_model_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2a4846ab-dc01-4e9f-81f0-5835f62d2b41'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
