# Generated by Django 5.0.3 on 2024-04-13 02:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0044_alter_user_model_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_model',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
